version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/gatsby-theme-carbon"
    schedule:
      interval: "daily"
      time: "17:29"
      timezone: "America/Chicago"
    allow:
      - dependency-name: "@carbon"
      - dependency-name: "carbon"
    reviewers:
      - "eng618"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "eng618"
